/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "squid.h"

bool_t
xdr_MoveReq (XDR *xdrs, MoveReq *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->player_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bridge_choice))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->jump))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GameState (XDR *xdrs, GameState *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (5 +  30 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->player_status))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->map, 30,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->time_left))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->survivors))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->current_bridge))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->current_step))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->player_status);
			{
				register int *genp;

				for (i = 0, genp = objp->map;
					i < 30; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->time_left);
			IXDR_PUT_LONG(buf, objp->survivors);
			IXDR_PUT_LONG(buf, objp->current_bridge);
			IXDR_PUT_LONG(buf, objp->current_step);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (5 +  30 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->player_status))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->map, 30,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->time_left))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->survivors))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->current_bridge))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->current_step))
				 return FALSE;
		} else {
			objp->player_status = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->map;
					i < 30; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->time_left = IXDR_GET_LONG(buf);
			objp->survivors = IXDR_GET_LONG(buf);
			objp->current_bridge = IXDR_GET_LONG(buf);
			objp->current_step = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->player_status))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->map, 30,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->time_left))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->survivors))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->current_bridge))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->current_step))
		 return FALSE;
	return TRUE;
}
