/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SQUID_H_RPCGEN
#define _SQUID_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct MoveReq {
	int player_id;
	int bridge_choice;
	int jump;
};
typedef struct MoveReq MoveReq;

struct GameState {
	int player_status;
	int map[30];
	int time_left;
	int survivors;
	int current_bridge;
	int current_step;
};
typedef struct GameState GameState;

#define SQUID_PROG 0x31230000
#define SQUID_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define JOIN_GAME 1
extern  int * join_game_1(void *, CLIENT *);
extern  int * join_game_1_svc(void *, struct svc_req *);
#define MOVE 2
extern  GameState * move_1(MoveReq *, CLIENT *);
extern  GameState * move_1_svc(MoveReq *, struct svc_req *);
#define GET_STATE 3
extern  GameState * get_state_1(int *, CLIENT *);
extern  GameState * get_state_1_svc(int *, struct svc_req *);
extern int squid_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JOIN_GAME 1
extern  int * join_game_1();
extern  int * join_game_1_svc();
#define MOVE 2
extern  GameState * move_1();
extern  GameState * move_1_svc();
#define GET_STATE 3
extern  GameState * get_state_1();
extern  GameState * get_state_1_svc();
extern int squid_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MoveReq (XDR *, MoveReq*);
extern  bool_t xdr_GameState (XDR *, GameState*);

#else /* K&R C */
extern bool_t xdr_MoveReq ();
extern bool_t xdr_GameState ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SQUID_H_RPCGEN */
